version = 1
SPDX-PackageName = "KDReports"
SPDX-PackageSupplier = "<info@kdab.com>"
SPDX-PackageDownloadLocation = "https://www.github.com/KDAB/KDReports"

#misc source code
[[annotations]]
path = ["**.qrc", "**.ui", "**.xml", "**.csv", "**.bat", "**.ts"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Klar채lvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>"
SPDX-License-Identifier = "MIT"

#artwork
[[annotations]]
path = ["images/**.png", "images/**.svg", "docs/api/**.png", "pics/**.png", "examples/**/**.png", "examples/**/**.jpg", "python/examples/**/**.jpg", "python/examples/**/**.png", "python/examples-qt6/**.jpg", "python/examples-qt6/**/**.png"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Klar채lvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>"
SPDX-License-Identifier = "MIT"

#misc documentation
[[annotations]]
path = ["**md", "**.txt", "**.html", "docs/manual/**.pdf"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Klar채lvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>"
SPDX-License-Identifier = "MIT"

#misc config files
[[annotations]]
path = [".pre-commit-config.yaml", ".codespellrc", ".krazy", ".cmake-format.py", ".clang-format", ".clang-tidy", ".clazy", ".gitignore", ".markdownlint.json", ".pep8", ".pylintrc", ".editorconfig", ".shellcheckrc", "docs/api/Doxyfile.cmake", "distro/**", "REUSE.toml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Klar채lvdalens Datakonsult AB, a KDAB Group company <info@kdab.com>"
SPDX-License-Identifier = "BSD-3-Clause"

#3rdparty
[[annotations]]
path = "cmake/ECM/modules/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "The KDE Project"
SPDX-License-Identifier = "BSD-3-Clause"

# doxygen awesome
[[annotations]]
path = "docs/api/doxygen-awesome.css"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 - 2023 jothepro"
SPDX-License-Identifier = "MIT"
